export const SET_SCREEN_NAME = 'SET_SCREEN_NAME';
export const VALIDATE_SCREEN_NAME = 'VALIDATE_SCREEN_NAME';
export const RUN_TEST = 'RUN_TEST';
export const SET_CURRENT_RESULTS = 'SET_CURRENT_RESULTS';
